"""
commands/run_cmd.py — cmd_run subcommand (tournament runner).
"""

import json
import os
import sys
from datetime import datetime
from pathlib import Path

from rich.panel import Panel
from rich.table import Table

from commands.shared import (
    ENGINE_ROOT,
    get_ai_backend,
    console,
    load_env,
    call_director,
    append_thinking_log,
    git_commit_batch,
    retire_principles,
)


def cmd_run(args):
    """Run the tournament in batches with optional AI direction."""
    domain_path = ENGINE_ROOT / args.domain

    if not domain_path.exists():
        print(f"Domain folder not found: {domain_path}")
        sys.exit(1)

    if getattr(args, "manual_ai", False):
        os.environ["AUTOFORGE_AI_BACKEND"] = "manual"

    # Load .env: domain folder first, then engine root as fallback
    load_env(domain_path)

    from engine_tournament import run_batch

    thinking_log = domain_path / "thinking_log.md"
    if not thinking_log.exists():
        thinking_log.write_text(
            f"# Thinking Log — {args.domain}\n\n"
            f"Started: {datetime.now().strftime('%Y-%m-%d %H:%M')}  "
            f"|  {args.batches} batches × {args.rounds} rounds\n\n---\n"
        )

    use_brain  = args.brain
    auto_mode  = getattr(args, "auto", False)
    brain_label = "Stage 2 — AI archetypes" if use_brain else ("auto" if auto_mode else "Stage 1 — procedural")
    backend_label = get_ai_backend()

    print(f"\n{'='*60}")
    print(f"Autoforge — {args.domain}  [{brain_label}]")
    if use_brain or auto_mode:
        print(f"AI backend: {backend_label}")
    print(f"{args.years} year(s) x {args.batches} batches x {args.rounds} rounds = {args.years * args.batches * args.rounds} total")
    print(f"{'='*60}\n")

    generation_offset     = 0
    year_avg_scores       = []
    prior_analysis        = None
    playbook_sizes        = []
    stop_reason           = None
    all_batch_rows        = []
    auto_consecutive_flat = 0
    hints                 = []
    adversarial_states    = []
    start_year            = 1
    start_batch           = 1
    run_id                = datetime.now().strftime("%Y%m%d-%H%M%S")

    # Sim hash — warn if simulation.py changed since last run
    import hashlib as _hashlib
    sim_path = domain_path / "simulation.py"
    if sim_path.exists():
        sim_hash = _hashlib.md5(sim_path.read_bytes()).hexdigest()[:8]
        pack_path = domain_path / "pack.json"
        pack_data = {}
        if pack_path.exists():
            try:
                pack_data = json.loads(pack_path.read_text())
            except Exception:
                pass
        stored_hash = pack_data.get("sim_hash")
        if stored_hash and stored_hash != sim_hash:
            print(f"[warn] simulation.py changed since last run ({stored_hash} → {sim_hash})")
            print("       Previous tournament_log.jsonl was generated by a different sim.")
            print("       Delete tournament_log.jsonl to start fresh, or continue if intentional.\n")
        pack_data["sim_hash"] = sim_hash
        if pack_path.exists():
            pack_path.write_text(json.dumps(pack_data, indent=2) + "\n")

    checkpoint_path = domain_path / "run_checkpoint.json"
    if checkpoint_path.exists():
        try:
            ckpt = json.loads(checkpoint_path.read_text())
            if ckpt.get("domain") == args.domain:
                generation_offset     = ckpt["generation_offset"]
                playbook_sizes        = ckpt["playbook_sizes"]
                prior_analysis        = ckpt.get("prior_analysis")
                auto_consecutive_flat = ckpt.get("auto_consecutive_flat", 0)
                use_brain             = ckpt.get("use_brain", use_brain)
                hints                 = ckpt.get("hints", [])
                all_batch_rows        = ckpt.get("all_batch_rows", [])
                year_avg_scores       = ckpt.get("year_avg_scores", [])
                start_year            = ckpt["year_num"]
                start_batch           = ckpt["batch_num"] + 1
                print(f"Resuming from batch {ckpt['global_batch']} (delete run_checkpoint.json to start fresh)\n")
        except Exception:
            pass

    for year_num in range(start_year, args.years + 1):
        all_results = []

        if args.years > 1:
            print(f"\n{'─'*60}")
            print(f"Year {year_num} / {args.years}  — playbook carries over from prior year")
            print(f"{'─'*60}\n")
            with open(thinking_log, "a") as f:
                f.write(f"\n# -- Year {year_num} -- {datetime.now().strftime('%Y-%m-%d %H:%M')} --\n\n")

        for batch_num in range(start_batch if year_num == start_year else 1, args.batches + 1):
            global_batch = (year_num - 1) * args.batches + batch_num

            # Auto-mode: promote to Stage 2 if playbook flatlined for 2 consecutive batches
            if auto_mode and not use_brain and auto_consecutive_flat >= 2:
                use_brain = True
                print(f"[auto] Playbook flat for 2 batches — promoting to Stage 2 (AI archetypes)\n")
                with open(thinking_log, "a") as f:
                    f.write(f"\n*[Auto] Stage 1 saturated at batch {global_batch} — promoted to Stage 2 (AI archetypes).*\n\n")

            print(f"[Y{year_num} Batch {batch_num}/{args.batches}] running {args.rounds} rounds", end="", flush=True)

            try:
                result = run_batch(
                    domain_path,
                    args.rounds,
                    generation_offset=generation_offset,
                    hints=hints,
                    use_brain=use_brain,
                    workers=args.workers,
                    run_id=run_id,
                    adversarial_states=adversarial_states,
                )
            except Exception as e:
                print(f"\n  [batch error: {e}] — skipping to next batch")
                with open(thinking_log, "a") as f:
                    f.write(f"\n*Batch {global_batch} failed: {e}*\n\n")
                generation_offset += args.rounds
                continue

            all_results.append(result)
            generation_offset += args.rounds

            # Track playbook sizes for saturation detection
            current_size = result["playbook_size"]
            playbook_sizes.append(current_size)

            # Auto-mode: track consecutive flat batches
            if auto_mode and not use_brain:
                if len(playbook_sizes) >= 2 and playbook_sizes[-1] == playbook_sizes[-2]:
                    auto_consecutive_flat += 1
                else:
                    auto_consecutive_flat = 0

            trend_char = "+" if result["trend_pct"] >= 0 else ""
            print(f"  ->  avg {result['avg_score']}  best {result['best_score']}  trend {trend_char}{result['trend_pct']:.1f}%")

            if use_brain:
                print(f"  director analyzing...", end="", flush=True)
                try:
                    analysis = call_director(global_batch, result, prior_analysis, all_results, domain_path, playbook_sizes)
                    append_thinking_log(thinking_log, global_batch, result, analysis)
                    verdict = analysis["verdict"]
                    print(f"  [{verdict}]")
                    print(f"  -> {analysis['next_batch_focus'][:80]}")
                    if analysis["concerns"]:
                        print(f"  ! {analysis['concerns'][0]}")
                    if verdict == "needs_calibration" and analysis.get("simulation_fix_suggestions"):
                        console.print("\n[yellow bold]Simulation fix suggestions:[/yellow bold]")
                        for fix in analysis["simulation_fix_suggestions"]:
                            console.print(f"  [yellow]• {fix}[/yellow]")
                        console.print(f"[dim]  Edit {args.domain}/simulation.py and re-run calibrate.[/dim]\n")
                except Exception as e:
                    print(f"  [director error: {e}] — continuing")
                    analysis = {"verdict": "exploring", "hints": hints, "retire_principles": [],
                                "next_batch_focus": "director unavailable — continuing previous hints",
                                "observations": [], "principles_gaining_confidence": [],
                                "concerns": [], "mistakes_to_note": [],
                                "simulation_fix_suggestions": []}
                    verdict = "exploring"
            else:
                # Stage 1 free mode — director only runs with --brain or after --auto promotion
                analysis = {"verdict": "exploring", "hints": [], "retire_principles": [],
                            "next_batch_focus": "Stage 1 — use --brain or --auto to enable director",
                            "observations": [], "principles_gaining_confidence": [],
                            "concerns": [], "mistakes_to_note": [],
                            "simulation_fix_suggestions": []}
                verdict = "exploring"
                print(f"  [Stage 1]")
            print()

            # Store row for summary table
            if len(all_batch_rows) > 0:
                prev_avg = all_batch_rows[-1]["avg"]
                trend_sym = "up" if result["avg_score"] > prev_avg else ("down" if result["avg_score"] < prev_avg else "flat")
            else:
                trend_sym = "--"
            all_batch_rows.append({
                "batch": global_batch,
                "avg":   result["avg_score"],
                "best":  result["best_score"],
                "trend": trend_sym,
            })

            hints          = analysis["hints"]
            prior_analysis = analysis

            retire_principles(analysis, domain_path)
            git_commit_batch(args.domain, domain_path, global_batch, result, analysis)

            # Generate adversarial scenarios every 2 Stage 2 batches for the next batch
            if use_brain and global_batch % 2 == 0:
                try:
                    from engine_brain import call_adversarial
                    champion = None
                    champ_path = domain_path / "champion_archetype.json"
                    if champ_path.exists():
                        champion = json.loads(champ_path.read_text())
                    adversarial_states = call_adversarial(
                        domain_path, n=args.rounds // 5,
                        context_mix=result.get("context_mix"),
                        champion=champion,
                    )
                    if adversarial_states:
                        print(f"  [adversarial] {len(adversarial_states)} targeted scenarios queued for next batch")
                except Exception:
                    adversarial_states = []
            elif not use_brain:
                adversarial_states = []

            checkpoint_path.write_text(json.dumps({
                "domain":               args.domain,
                "generation_offset":    generation_offset,
                "global_batch":         global_batch,
                "batch_num":            batch_num,
                "year_num":             year_num,
                "use_brain":            use_brain,
                "hints":                hints,
                "prior_analysis":       prior_analysis,
                "playbook_sizes":       playbook_sizes,
                "auto_consecutive_flat": auto_consecutive_flat,
                "all_batch_rows":       all_batch_rows,
                "year_avg_scores":      year_avg_scores,
                "timestamp":            datetime.now().isoformat(),
            }, indent=2))

            if verdict == "reward_hacking":
                print("! Reward hacking flagged — stopping run.")
                fixes = analysis.get("simulation_fix_suggestions", [])
                if fixes:
                    console.print("\n[red bold]Simulation fix suggestions:[/red bold]")
                    for fix in fixes:
                        console.print(f"  [red]• {fix}[/red]")
                    console.print(f"\n[dim]Edit {args.domain}/simulation.py, then re-run calibrate.[/dim]")
                else:
                    print(f"  Check thinking_log.md for details.")
                stop_reason = "reward_hacking"
                year_avg_scores.append(round(sum(r["avg_score"] for r in all_results) / len(all_results), 2))
                break

            if verdict == "saturated":
                print("Playbook saturated — engine has learned everything this sim can teach.")
                print("Run:  python run.py export --domain " + args.domain)
                stop_reason = "saturated"
                year_avg_scores.append(round(sum(r["avg_score"] for r in all_results) / len(all_results), 2))
                break

        else:
            year_avg_scores.append(round(sum(r["avg_score"] for r in all_results) / len(all_results), 2))

        if stop_reason in ("reward_hacking", "saturated"):
            break

    # Clean up checkpoint on normal completion
    if checkpoint_path.exists() and stop_reason not in ("reward_hacking",):
        checkpoint_path.unlink()

    # Write last_run.json
    final_verdict = prior_analysis["verdict"] if prior_analysis else "unknown"
    last_run = {
        "timestamp":    datetime.now().isoformat(),
        "domain":       args.domain,
        "total_rounds": generation_offset,
        "year_avg_scores": year_avg_scores,
        "final_verdict":   final_verdict,
        "stop_reason":     stop_reason,
    }
    (domain_path / "last_run.json").write_text(json.dumps(last_run, indent=2))

    # Terminal bell
    print("\a", end="", flush=True)

    # Rich summary
    table = Table(title=f"Run Summary — {args.domain}", show_header=True)
    table.add_column("Batch", style="dim", width=6)
    table.add_column("Avg", justify="right")
    table.add_column("Best", justify="right")
    table.add_column("Trend", justify="center")
    for row in all_batch_rows:
        trend_display = {"up": "[green]up[/green]", "down": "[red]down[/red]", "flat": "flat", "--": "--"}.get(row["trend"], row["trend"])
        table.add_row(str(row["batch"]), str(row["avg"]), str(row["best"]), trend_display)
    console.print()
    console.print(table)

    verdict_color = {
        "converging": "green", "saturated": "green", "exploring": "yellow",
        "stalled": "yellow", "reward_hacking": "red", "needs_calibration": "red",
    }.get(final_verdict, "white")
    panel_content = f"[{verdict_color}]Verdict: {final_verdict}[/{verdict_color}]"
    if stop_reason:
        panel_content += f"\nStop reason: {stop_reason}"
    if prior_analysis and prior_analysis.get("concerns"):
        panel_content += f"\nTop concern: {prior_analysis['concerns'][0]}"
    panel_content += f"\nThinking log: {thinking_log}"
    console.print(Panel(panel_content, title="Final State"))

    # Print champion archetype if it exists
    champion_path = domain_path / "champion_archetype.json"
    if champion_path.exists():
        try:
            champ = json.loads(champion_path.read_text())
            print(f"Champion: {champ.get('name', 'unknown')}")
            print(f"  {champ.get('philosophy', '')}")
        except Exception:
            pass
